default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
      - id: validate-schema
        name: validate schema
        entry: ./script/validate.py
        language: python
        additional_dependencies: [jsonschema, pyyaml]
        pass_filenames: false
        always_run: true
